// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using web_api.Models;

namespace web_api.Migrations
{
    [DbContext(typeof(web_apiContext))]
    partial class web_apiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("web_api.Models.Exercise", b =>
                {
                    b.Property<long>("ExerciseId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("Reps");

                    b.Property<int>("Sets");

                    b.Property<long?>("WorkoutId");

                    b.Property<long?>("WorkoutLogId");

                    b.HasKey("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.HasIndex("WorkoutLogId");

                    b.ToTable("Exercise");
                });

            modelBuilder.Entity("web_api.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("web_api.Models.Workout", b =>
                {
                    b.Property<long>("WorkoutId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("WorkoutId");

                    b.ToTable("Workout");
                });

            modelBuilder.Entity("web_api.Models.WorkoutLog", b =>
                {
                    b.Property<long>("WorkoutLogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Date");

                    b.HasKey("WorkoutLogId");

                    b.ToTable("WorkoutLog");
                });

            modelBuilder.Entity("web_api.Models.Exercise", b =>
                {
                    b.HasOne("web_api.Models.Workout")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId");

                    b.HasOne("web_api.Models.WorkoutLog")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutLogId");
                });
#pragma warning restore 612, 618
        }
    }
}
